CREATE TABLE PASSENGER
(
  PASSENGER_ID int PRIMARY KEY,
  Username varchar(255) UNIQUE NOT NULL,
  Password varchar(255) UNIQUE NOT NULL,
  Carnet varchar(255) UNIQUE,
  Millas int,
  Email varchar(255),
  Passport varchar(255) UNIQUE NOT NULL,
  Age int,
  FirstName varchar(255) NOT NULL,
  MI varchar(255),
  LastName varchar(255) NOT NULL,
  Credit_Card_ID int,
  Trip_ID int,
  Phone_ID int,
  BoardingPass_ID int
);

CREATE TABLE UNIVERSITY
(
  UNIVERSITY_ID int PRIMARY KEY,
  UniversityName varchar(255) UNIQUE NOT NULL
);

CREATE TABLE ENROLLED_RELATION
(
  ENROLLED_RELATION_ID int PRIMARY KEY,
  Passenger_ID int,
  University_ID int
);

CREATE TABLE PHONE
(
  PHONE_ID int PRIMARY KEY,
  CountryCode int NOT NULL,
  PhoneNumber int NOT NULL,
  PhoneType varchar(255)
);

CREATE TABLE CREDIT_CARD
(
  CREDIT_CARD_ID int PRIMARY KEY,
  CardNumber int UNIQUE NOT NULL,
  CardName int NOT NULL,
  ExpDate date NOT NULL
);

CREATE TABLE COUNTRY
(
  COUNTRY_ID int PRIMARY KEY,
  CountryName varchar(255) UNIQUE NOT NULL
);

CREATE TABLE CITY
(
  CITY_ID int PRIMARY KEY,
  CityName varchar(255) NOT NULL,
  Country_ID int
);

CREATE TABLE AIRPORT
(
  AIRPORT_ID int PRIMARY KEY,
  AirportCode varchar(255) UNIQUE NOT NULL,
  City_ID int
);

CREATE TABLE PROMOTION
(
  PROMOTION_ID int PRIMARY KEY,
  PromotionName varchar(255) NOT NULL,
  StartDate date NOT NULL,
  EndDate date NOT NULL
);

CREATE TABLE BOARDINGPASS
(
  BOARDINGPASS_ID int PRIMARY KEY,
  Price int NOT NULL,
  Class varchar(255) NOT NULL,
  Flight_ID int,
  Seat_ID int,
  Plane_ID int
);

CREATE TABLE FLIGHT
(
  FLIGHT_ID int PRIMARY KEY
  InitialTime date not NULL
  FinalTime date not NULL
);

CREATE TABLE SOURCE_RELATION
(
  SOURCE_RELATION_ID int PRIMARY KEY,
  Airport_ID int,
  Flight_ID int
);

CREATE TABLE DESTINATION_RELATION
(
  DESTINATION_RELATION_ID int PRIMARY KEY,
  Airport_ID int,
  Flight_ID int
);

CREATE TABLE START_RELATION
(
  START_RELATION_ID int PRIMARY KEY,
  Airport_ID int,
  Trip_ID int
);

CREATE TABLE END_RELATION
(
  END_RELATION_ID int PRIMARY KEY,
  Airport_ID int,
  Trip_ID int
);

CREATE TABLE TRIP
(
  TRIP_ID int PRIMARY KEY,
  Flight_ID int,
  Promotion_ID int
);

CREATE TABLE SEAT
(
  SEAT_ID int PRIMARY KEY,
  SeatNumber int NOT NULL
);

CREATE TABLE ARCHETYPE
(
  ARCHETYPE_ID int PRIMARY KEY,
  NumberOfSeats int NOT NULL,
);

CREATE TABLE PLANE
(
  PLANE_ID int PRIMARY KEY,
  Archetype_ID int
);

CREATE TABLE STORED_IN_RELATION
(
  STORED_IN_ID int PRIMARY KEY,
  Plane_ID int,
  Airport_ID int
);

CREATE TABLE EMPLOYEE
(
  EMPLOYEE_ID int PRIMARY KEY,
  Username varchar(255) UNIQUE NOT NULL,
  Password varchar(255) NOT NULL,
  FirstName varchar(255) NOT NULL,
  MI varchar(255),
  LastName varchar(255) NOT NULL,
  Job_ID int
);

CREATE TABLE JOB
(
  JOB_ID int PRIMARY KEY,
  JobDescription varchar(255) UNIQUE
);

ALTER TABLE PASSENGER ADD FOREIGN KEY (Credit_Card_ID) REFERENCES CREDIT_CARD (CREDIT_CARD_ID);

ALTER TABLE PASSENGER ADD FOREIGN KEY (Trip_ID) REFERENCES TRIP (TRIP_ID);

ALTER TABLE PASSENGER ADD FOREIGN KEY (Phone_ID) REFERENCES PHONE (PHONE_ID);

ALTER TABLE PASSENGER ADD FOREIGN KEY (BoardingPass_ID) REFERENCES BOARDINGPASS (BOARDINGPASS_ID);

ALTER TABLE ENROLLED_RELATION ADD FOREIGN KEY (Passenger_ID) REFERENCES PASSENGER (PASSENGER_ID);

ALTER TABLE ENROLLED_RELATION ADD FOREIGN KEY (University_ID) REFERENCES UNIVERSITY (UNIVERSITY_ID);

ALTER TABLE CITY ADD FOREIGN KEY (Country_ID) REFERENCES COUNTRY (COUNTRY_ID);

ALTER TABLE AIRPORT ADD FOREIGN KEY (City_ID) REFERENCES CITY (CITY_ID);

ALTER TABLE BOARDINGPASS ADD FOREIGN KEY (Flight_ID) REFERENCES FLIGHT (FLIGHT_ID);

ALTER TABLE BOARDINGPASS ADD FOREIGN KEY (Seat_ID) REFERENCES SEAT (SEAT_ID);

ALTER TABLE SOURCE_RELATION ADD FOREIGN KEY (Airport_ID) REFERENCES AIRPORT (AIRPORT_ID);

ALTER TABLE SOURCE_RELATION ADD FOREIGN KEY (Flight_ID) REFERENCES FLIGHT (FLIGHT_ID);

ALTER TABLE DESTINATION_RELATION ADD FOREIGN KEY (Airport_ID) REFERENCES AIRPORT (AIRPORT_ID);

ALTER TABLE DESTINATION_RELATION ADD FOREIGN KEY (Flight_ID) REFERENCES FLIGHT (FLIGHT_ID);

ALTER TABLE START_RELATION ADD FOREIGN KEY (Airport_ID) REFERENCES AIRPORT (AIRPORT_ID);

ALTER TABLE START_RELATION ADD FOREIGN KEY (Trip_ID) REFERENCES TRIP (TRIP_ID);

ALTER TABLE END_RELATION ADD FOREIGN KEY (Airport_ID) REFERENCES AIRPORT (AIRPORT_ID);

ALTER TABLE END_RELATION ADD FOREIGN KEY (Trip_ID) REFERENCES TRIP (TRIP_ID);

ALTER TABLE TRIP ADD FOREIGN KEY (Flight_ID) REFERENCES FLIGHT (FLIGHT_ID);

ALTER TABLE TRIP ADD FOREIGN KEY (Promotion_ID) REFERENCES PROMOTION (PROMOTION_ID);

ALTER TABLE PLANE ADD FOREIGN KEY (Archetype_ID) REFERENCES ARCHETYPE (ARCHETYPE_ID);

ALTER TABLE STORED_IN_RELATION ADD FOREIGN KEY (Plane_ID) REFERENCES PLANE (PLANE_ID);

ALTER TABLE STORED_IN_RELATION ADD FOREIGN KEY (Airport_ID) REFERENCES AIRPORT (AIRPORT_ID);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (Job_ID) REFERENCES JOB (JOB_ID);
